/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DabRhythm;

import Core.App;
import Core.Engine;
import Entities.EntityManager;
import Graphics.ProjectionMatrix;
import Graphics.Batch.SpriteBatch;
import Graphics.Models.Texture;
import Menus.MainMenu;
import Scenes.IntroScene;
import Scenes.MenuScene;
import Scenes.Scene;
import Scenes.SceneManager;
import Scenes.SongBrowserScene;
import System.RenderSystem;

import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.glfw.GLFW.*;

import java.util.HashMap;
import Graphics.Graphics;

public class Main extends App {

    public static final Engine engine = new Engine();
    private Graphics graphics;

    {
        WIDTH = 800;
        HEIGHT = 600;
        TITLE = "DabRhythm";
        hints = new HashMap<>() {
            {
                put(GLFW_RESIZABLE, 0);
            }
        };
        fullscreen = false;
    }

    public void init() {
        ProjectionMatrix.createProjectionMatrix2D(0, engine.getMainWindow().getWidth(),
                engine.getMainWindow().getHeight(), 0);
        graphics = engine.createGraphics();

        Beats.updateList();
        Skins.updateSkins();
        SkinLoader.load("Default Skin");

        SceneManager.addScene(new IntroScene());
        SceneManager.addScene(new MenuScene());
        SceneManager.addScene(new SongBrowserScene());

        SceneManager.setCurrentScene(SceneManager.getScene(IntroScene.class));
    }

    public void render() {
        glClear(GL_COLOR_BUFFER_BIT);
        SceneManager.getCurrentScene().render(graphics);
    }

    public void update() {
        SceneManager.getCurrentScene().tick();
        //System.out.println(EntityManager.entities.toString());
    }

    public static void main(String[] args) {
        engine.init(new Main());
        engine.run();
    }

    public static class Config {

        public static int left_arrow_button = GLFW_KEY_D, 
        up_arrow_button = GLFW_KEY_F, 
        down_arrow_button = GLFW_KEY_J, 
        right_arrow_button = GLFW_KEY_K;
    }

    public static class Skin {

        public static String skin_name;

        public static final Texture[] mania_key = new Texture[4];
        public static final Texture[] mania_key_down = new Texture[4];
        public static final Texture[] note = new Texture[4];

        public static final Texture[] score = new Texture[10];
        public static final Texture[] normal = new Texture[10];
        public static final Texture[] combo = new Texture[10];

        public static Texture score_percent;
        public static Texture score_x;

        public static final Texture[] count = new Texture[3];
        public static Texture go;

    }
}
